# from Ansible Galaxy
- name: aws-cli
  src: badpacketsllc.aws_cli
  version: v1.0.2
- name: datadog
  src: Datadog.datadog
  version: 4.11.0
- name: docker
  src: nickjj.docker
  version: v1.9.1
- name: nginx
  src: geerlingguy.nginx
  version: 2.7.0


# from git
- name: docker-compose-openmrs
  src: https://github.com/openmrs/openmrs-contrib-ansible-docker-compose.git
- name: dhparam
  src: https://github.com/gronke/ansible-dhparam.git
  version: 9a24d9610f5b88458a27ce0df1dca9a4ccdfaa1e
- name: letsencrypt
  src: https://github.com/thefinn93/ansible-letsencrypt
  version: 45a305261ba84eb31e23b85edb4030049a3e623f
- name: sudo
  src: https://github.com/yatesr/ansible-sudo.git
  version: 2a55007541a2f340eec57e4e5a7efa1c3fc73d74
- name: timezone
  src: https://github.com/yatesr/ansible-timezone.git
  version: 854af629e6740c92b9098026148906643a13465c
- name: ufw
  src: https://github.com/yatesr/ansible-ufw.git
  version: f0f7615a9b1c03f29d501e169caa9ea2538cdded
- name: users
  src: https://github.com/cintiadr/ansible-users.git
  version: 0986a64bd243c9181e0245580e39ee23bdedf546
- name: jira
  src: https://github.com/cintiadr/ansible-role-jira
  version: 93088485710837791aba08179449700cabda10c3
- name: mysql-connector-java
  src: https://github.com/cintiadr/ansible-role-mysql-connector-java.git
  version: 7a9ecef6bde1fdc890b755c179a87bbe7e597dcd
- name: confluence
  src: https://github.com/cintiadr/ansible-role-confluence.git
  version: 402551f5975dda36239b21163517e4472891f561
- name: bamboo
  src: https://github.com/cintiadr/ansible-role-bamboo.git
  version: 2fc0a8e84c0ddfbe5fcd4b2f4232db25cad86208
- name: crowd
  src: https://github.com/cintiadr/ansible-role-crowd.git
  version: 5e24c59a607ec65f3cbd59d2876209e5a331f0d6
- name: logrotate
  src: https://github.com/nickhammond/ansible-logrotate
  version: 91d570f68c44261d2051a99a2b3c7d736306bf0d
