---
# Master Playbook

- hosts: all
  become: true
  tags:
    - basic-os
  tasks:
   - include: tasks/hostname.yml # should happen before installing datadog
   - include: tasks/updates.yml
   - include: tasks/cleanup.yml

- hosts: all
  become: true
  tags:
    - soe
  roles:
   - { role: 'custom_roles/users' }
   - sudo
   - { role: 'custom_roles/sshd' }
   - ufw
   - datadog
  tasks:
    - include: tasks/extra-monitoring.yml
  handlers:
    - include: handlers/monitoring.yml

- hosts: vagrant
  become: true
  tags:
    - vagrant
  roles:
    - logrotate

- hosts: tls
  tags:
    - tls
  become: true
  tasks:
    - include: tasks/extra-tls.yml
  roles:
    - dhparam
    - { role: 'custom_roles/letsencrypt'}
  handlers:
    - include: handlers/monitoring.yml

- hosts: web
  become: true
  tags:
    - web
  roles:
   - nginx

- hosts: backup
  become: true
  tags:
   - backup
  tasks:
   - include: tasks/backup.yml
  roles:
   - aws-cli
  handlers:
    - include: handlers/monitoring.yml

- hosts: docker
  become: true
  tags:
   - docker
  pre_tasks:
   - include: tasks/docker-config.yml
  roles:
   - docker-compose-openmrs
  handlers:
    - include: handlers/monitoring.yml

- hosts: jira
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  # roles:
  #   - jira
  #   - mysql-connector-java
  tags:
    - jira

- hosts: confluence
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  # roles:
  #   - confluence
  #   - mysql-connector-java
  tags:
    - confluence

- hosts: bamboo
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - bamboo
    - mysql-connector-java
    - logrotate
  tags:
    - bamboo

- hosts: bambooagent
  become: true
  tasks:
   - include: tasks/bamboo-agent.yml
  tags:
    - bambooagent

- hosts: crowd
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - crowd
    - mysql-connector-java
  tags:
    - crowd

- hosts: mysql
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - mysql
  roles:
    - { role: 'custom_roles/mysql' }
    - { role: 'custom_roles/mysql-cron-backup' }

- hosts: discourse
  tags:
    - discourse
  become: true
  roles:
    - { role: 'custom_roles/docker-discourse' }
